### ISSUE TITLE
Add link english book - intelligent business elementary coursebook

### ISSUE THREAD

**Issue by adammacias** [fatechub/fatecrl-curso-si#28]
http://pt.slideshare.net/DanielaSalvade/intelligentbusinesselementarycoursebook

**Comment by flaviacs** [comment]
Legal achar o livro, mas ela falou que vai mesclar com outro.

**Comment by adammacias** [comment]
Na verdade, ela disse que pegaria só alguns capitulos, mas não custa botar o PDF aqui =)
